// Generated by CoffeeScript 1.8.0
(function() {
  var Log, test;

  Log = require("../lib/log");

  test = function() {
    return Log.debug([1, 2, 3, 4], {
      a: 1
    });
  };

  test();

}).call(this);
