// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    log2console: true,
    timestamp: "MM-DD HH:mm:ss",
    levelShow: true,
    lineInfo: false,
    log2file: false
  };

}).call(this);
