// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    "log2console": true,
    "timestamp": "YYYY-MM-DD HH:mm:ss",
    "levelShow": true,
    "lineInfo": {
      "error": true,
      "debug": true
    },
    "log2file": true,
    "dirRoot": false,
    "dirs": false,
    "default_dir": "logs",
    "filename": "$YYYYMMDD",
    "levelfile": false
  };

}).call(this);
