// Generated by CoffeeScript 1.7.1
(function() {
  var Log2File, createDir, cwd, dirname, getDirName, _config, _mkdirp, _moment, _path;

  _config = require('./config.json');

  _mkdirp = require('mkdirp');

  _moment = require('moment');

  _path = require('path');

  Log2File = {};

  Log2File.init = function(config) {
    return _config = config;
  };

  dirname = "logs";

  cwd = process.cwd();

  getDirName = function() {
    var d, dirs, _i, _len, _ref;
    dirs = _config.dirRoot && typeof _config.dirRoot === 'string' ? [_config.dirRoot] : [cwd];
    if (!_config.dirs || !_config.dirs.length) {
      return dirs;
    }
    if (typeof _config.dirs === 'string') {
      dirs.push(_config.dirs);
      return dirs;
    }
    _ref = _config.dirs;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      d = _ref[_i];
      if (d.indexOf('$') !== 0) {
        dirs.push(d);
        continue;
      }
      dirs.push(_moment().format(d.replace('$', '')));
    }
    return dirs;
  };

  createDir = function() {
    var dirName;
    dirName = _path.join.apply(this, getDirName());
    console.log(dirName);
    return _mkdirp.sync(dirName);
  };

  module.exports = {
    createDir: createDir
  };

}).call(this);
