// Generated by CoffeeScript 1.7.1
(function() {
  var Log, factory, format, getFileAndLine, init, isSupport, logfile, output2Console, output2file, _colors, _config, _moment;

  _colors = require('colors');

  _config = require('./config.json');

  _moment = require('moment');

  logfile = require('./file');

  _colors.setTheme({
    info: 'green',
    help: 'cyan',
    warn: 'yellow',
    debug: 'blue',
    error: 'red'
  });

  isSupport = (function() {
    var err;
    err = new Error();
    if (!err.stack) {
      return console.log("The version of node  do not support slow4js".warn);
    }
    return true;
  })();

  getFileAndLine = function() {
    var cwd, fileInfo, info, reg, stack;
    if (!isSupport) {
      return '';
    }
    stack = new Error().stack;
    info = stack.split('\n')[3];
    cwd = process.cwd();
    if (!info) {
      return '';
    }
    reg = new RegExp("" + cwd + "([^:])+:\\d", "g");
    if (fileInfo = info.match(reg)[0]) {
      return fileInfo.replace(cwd, '');
    }
    return '';
  };

  format = function(lineInfo, content, type) {
    var loginfo;
    loginfo = [];
    if (_config.timestamp) {
      loginfo.push(_moment().format(_config.timestamp));
    }
    if (_config.lineInfo) {
      loginfo.push(lineInfo);
    }
    if (_config.levelShow) {
      loginfo.push("[" + (type.toUpperCase()) + "]");
    }
    loginfo.push(content);
    return loginfo.join(' ');
  };

  output2Console = function(content, type) {
    if (_config.log2console && _config.log2console[type]) {
      return console.log(content[type]);
    }
  };

  output2file = function(content, type) {};

  init = function(custom) {
    var property;
    if (!custom) {
      return _config;
    }
    for (property in custom) {
      _config[property] = custom[property];
    }
    logfile.init(_config);
    return _config;
  };

  Log = {};

  factory = function(type) {
    return function(content) {
      var lineinfo;
      lineinfo = getFileAndLine();
      if (!content) {
        return;
      }
      content = format(lineinfo, content, type);
      return output2Console(content, type);
    };
  };

  Log.warn = factory('warn');

  Log.error = factory('error');

  Log.info = factory('info');

  Log.debug = factory('debug');

  Log.init = init;

  module.exports = Log;

}).call(this);
