// Generated by CoffeeScript 1.7.1
(function() {
  var Log, colors, factory;

  colors = require('colors');

  colors.setTheme({
    info: 'green',
    help: 'cyan',
    warn: 'yellow',
    debug: 'blue',
    error: 'red'
  });

  Log = {};

  factory = function(type) {
    return function(content) {
      if (!content) {
        return;
      }
      return console.log(content[type]);
    };
  };

  Log.warn = factory('warn');

  Log.error = factory('error');

  Log.info = factory('info');

  Log.success = factory('help');

  module.exports = Log;

}).call(this);
