// Generated by CoffeeScript 1.7.1
(function() {
  var Log, test;

  Log = require("./log");

  test = function() {
    Log.info('hello');
    Log.error(new Error('hello'));
    Log.warn({
      a: 1,
      b: 2
    });
    Log.debug([1, 2, 3, 4]);
    Log.info([1, 2, 3, 4]);
    Log.info('hello', 'world');
    Log.info({
      a: 1,
      b: 2
    }, [12, 23, 34]);
    Log.info({
      a: 1,
      b: 2
    }, [12, 23, 34], new Error('hello'));
    return Log.info({
      a: 1,
      b: 4
    }, "hello ?", 123);
  };

  test();

}).call(this);
