// Generated by CoffeeScript 1.7.1
(function() {
  var Log, logfile, test;

  Log = require("./log");

  logfile = require("./file");

  test = function() {
    Log.error("this is error");
    Log.debug("this is success");
    Log.warn("this is warn");
    return Log.info("this is info");
  };

  test();

}).call(this);
